name: DHHF Bot

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install yfinance python-telegram-bot pytz

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AVERAGE_COST: ${{ secrets.AVERAGE_COST }}
          MONTHLY_AMOUNT: ${{ secrets.MONTHLY_AMOUNT }}
          BONUS_AMOUNT: ${{ secrets.BONUS_AMOUNT }}
          MONTHLY_BUDGET: ${{ secrets.MONTHLY_BUDGET }}
        run: python bot.py
